### PR TITLE
Add zh-cn translation

### PR DESCRIPTION
**Pull request by hedonihilist**
It's a great plugin and I can't help translating it into zh-cn!

Noticed that only parts of the text were translated, any plan to fully support i18n?
image

### CODE REVIEW

**Comment by RafaelGB** [comment]
hello! until now I was not translating all the messages since nobody was requesting it, but with your PR I will try to add all the messages in the near future

I really appreciate your contribution!

**Review by RafaelGB — APPROVED** [review]

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/679 I will support it here =)

**Comment by RafaelGB** [comment]
with "Commit d63f9f82" a lot of new labels were included

**Comment by hedonihilist** [comment]
> 

will take a look and add some translation 😸

**Pull request merged**
